---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: crashtein/frontend:latest
        name: frontend
        ports:
        - containerPort: 5000
        env:
          - name: BACKEND_URL
            value: "backend:5001"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend-service
spec:
  ports:
  - name: frontend
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30080
  selector:
    app: frontend
  type: NodePort
